seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  # strategy: ddp # or ddp_find_unused_parameters
  devices: [0]
  num_nodes: 1
  precision: bf16 # or 32, or 16
  max_epochs: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 5

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/fewshot.GTZANGenre.MERT-v1-95M/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: -1 # -1 to save all checkpoints
        monitor: "val/acc"  # Monitor validation accuracy
        mode: "max"  # We want to maximize accuracy
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "fewshot.GTZANGenre.MERT-v1-95M"
      save_dir: "./output/fewshot.GTZANGenre.MERT-v1-95M/"


model:
  class_path: marble.tasks.GTZANGenre.fewshot.FewShotAudioTask
  init_args:
    sample_rate: 24000
    num_classes: 10

    encoder:
      class_path: marble.encoders.MERT.model.MERT_v1_95M_Encoder
      init_args:
        pre_trained_folder: null
        train_mode: freeze  # also supports lora, or full
        force_half: false
        preprocess_in_forward: false
      
    emb_transforms:
      - class_path: marble.modules.transforms.LayerSelector
        init_args:
          layers: [7]  # something like [1, 3, "10..72"]
      - class_path: marble.modules.transforms.TimeAvgPool # (batch_size, num_layers, 1, hidden_size)
    
data:
  class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreDataModule
  init_args:
    batch_size: 8
    num_workers: 8

    audio_transforms:
      train:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true
      val:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true
      test:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true

    train:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioTrain
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8 # at least 80% of the clip length
        channel_mode: first # first, random, mix
        jsonl: data/GTZAN/GTZANGenre.train.jsonl
    val:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioVal
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/GTZAN/GTZANGenre.val.jsonl
    test:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioTest
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/GTZAN/GTZANGenre.test.jsonl

