# =============================================================================
# 1. EMO Task (Emotion Regression) - probe.EMO.TransformerSegment.yaml
# =============================================================================
seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  devices: [0]
  accumulate_grad_batches: 4  # 원래대로 복원
  num_nodes: 1
  precision: bf16
  max_epochs: 50
  check_val_every_n_epoch: 1  # 원래대로 복원
  num_sanity_val_steps: 0  # sanity check 비활성화 (R2 오류 방지)
  log_every_n_steps: 5

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/probe.EMO.TransformerSegment/checkpoints/"
        filename: "best"
        save_top_k: 1
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/r2"
        patience: 20
        mode: "max"
    - class_path: marble.encoders.transformer_segment_encoder.TransformerStatsCallback  # 통계 콜백 추가
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "probe.EMO.TransformerSegment"
      save_dir: "./output/probe.EMO.TransformerSegment/"

model:
  class_path: marble.tasks.EMO.probe.ProbeAudioTask
  init_args:
    sample_rate: 24000
    use_ema: false

    encoder:
      class_path: marble.encoders.transformer_segment_encoder.TransformerSegmentEncoder
      init_args:
        muq_model_name: "OpenMuQ/MuQ-large-msd-iter"
        transformer_checkpoint_path: "/home/jay/MusicAI/transformer_60sec_mlm.pth"
        target_sr: 24000
        muq_segment_seconds: 60  # MuQ 처리용 60초 세그먼트
        min_samples_threshold: 2048
        emb_dim: 1024
        heads: 8
        hidden: 1024
        layers: 4
        max_len: 100000
        dropout: 0.1
      
    emb_transforms: []  # No additional transforms needed
    
    decoders:
      - class_path: marble.modules.decoders.MLPDecoder
        init_args:
          in_dim: 1024  # Transformer output dimension
          out_dim: 2   # arousal + valence
          hidden_layers: [512]
          activation_fn: 
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      - class_path: torch.nn.MSELoss
        init_args:
          reduction: mean

    metrics:
      train:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
      val:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
      test:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
    
data:
  class_path: marble.tasks.EMO.datamodule.EMODataModule
  init_args:
    batch_size: 16  # MuQ 모델과 동일하게 설정
    num_workers: 4

    train:
      class_path: marble.tasks.EMO.datamodule.EMOAudioTrain
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/EMO/EMO.train.jsonl
    val:
      class_path: marble.tasks.EMO.datamodule.EMOAudioVal
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/EMO/EMO.val.jsonl
    test:
      class_path: marble.tasks.EMO.datamodule.EMOAudioTest
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/EMO/EMO.test.jsonl

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.5
    patience: 5
    monitor: "val/r2"
